server:
  port: 1100
spring:
  application:
    name: zuul-server
zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plat/** #平台服务的请求路径
      serviceId: plat-service
      path: /product/**
      serviceId: product-server
  prefix: /services #请求前